name = "my-worker"
type = "webpack"


account_id = "b3b6a9170e95e7d2694f728cfe832d2b"
workers_dev = true
route = "https://my-worker.airbenderosp7770.workers.dev/"
zone_id = ""
compatibility_date = "2022-03-01"

[env.production]
kv_namespaces = [ 
         { binding = "cloud_kv", id = "f78bca3c2daf48efb6100e1ee1b2b324" }
]
